### ISSUE TITLE
Is it possible to annotate Kotlin entity classes?

### ISSUE THREAD

**Issue by jjzazuet** [OnyxDevTools/onyx-database-parent#94]
Hi. I'm new to this framework, liking it thus far!

In the documentation, I see the main examples using a regular POJO with getters and setters. 

Can we define our entities as Kotlin classes as well? Do the persistence engines support it?

My apologies if this comes as an uninformed question. I just started learning Kotlin, so I'm not completely sure of what's possible and what's not. If there's any documentation which addresses this question, I'll be happy to read any bookmarks available. 

Thanks again!

**Comment by jjzazuet** [comment]
Much appreciated. 

It seems as if the [Address](https://github.com/OnyxDevTools/onyx-database-parent/blob/develop/onyx-database-tests/src/main/kotlin/entities/Address.kt) entity is a good starting point. Should I keep this issue open as a work item to add more documentation? Or do you guys track such items elsewhere?

Thanks again!

**Comment by timbob1000** [comment]
Leave this issue open.  I will close it after adding the documentation / examples.  

Github is the correct place.  It just happens to be the only open issue at the moment.

Tim
