### ISSUE TITLE
Creation of encrypted database

### ISSUE THREAD

**Issue by HomaHn** [OnyxDevTools/onyx-database-parent#96]
Hi,
I am new in onyx database,
I see the examples and run following examples in Netbeans IDE:
https://github.com/OnyxDevTools/onyx-database-parent/tree/develop/onyx-database-examples/querying
database created in my system and when myDB.dat opened ,all data are plain in myDB.dat and not encrypted.
I want to encrypt data in database file, Is there an encryption feature data in onyx database?
whats example for this feature?

**Comment by timbob2000** [comment]
Encryption will be available in the next release
